apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-example
  labels:
    app: k8s-example
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-example
      tier: backend
  template:
    metadata:
      labels:
        app: k8s-example
        tier: backend
    spec:
      containers:
      - name: k8s-example
        image: lusyoe/k8s-example
        env:
          - name: CLUSTER
            value: {{ .Values.clustername }}
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
